export let portfolio = [
    {displayName: "kazoot", blurb: "Every bus ticket you'll ever need", docId: "kazoot", img:"kazoot"},
    {displayName: "Bus Open Data API", blurb: "API as a service for every bus operator to power travel apps", docId: "bods", img:"bods"},
    {displayName: "Contactless", blurb: "Tap On Tap Off (the bus): TOTO we're not in Kansas anymore", docId: "contactless", img:"contactless"},
    {displayName: "D.R.T.", blurb: "Demand Responsive Transport, i.e. Shared Taxi but the Taxi is a Bus", docId: "drt", img:"drt"},
    {displayName: "Safety Checklists", blurb: "Digital safety checks", docId: "checklist", img:"checklist"},
    {displayName: "Internationalization", blurb: "Going from 1 locality to 2 makes going to ∞ possible", docId: "international", img:"international"},
    {displayName: "Ticketer Realtime", blurb: "Tracking thousands of buses, their tickets and their punctuality", docId: "realtime", img:"realtime"},
    {displayName: "Go4venture", blurb: "A syndication and research platform for European Startups", docId: "go4", img:"go4"},
    {displayName: "Issran", blurb: "Why not waste time by learning instead?", docId: "kazoot", img:"issran"},
    {displayName: "Day Buffer", blurb: "Shouldn't you be able to quickly see what you've done with your life?", docId: "daybuffer", img:"daybuffer"},
    {displayName: "Passwordless SQLite", blurb: "Passwordless didn't have a sqlite token store so I built one ", docId: "passwordless", img:"passwordless"},
    {displayName: "Metalize", blurb: "Make your web browsing more metal, with Metalize!", docId: "metalize", img:"metallize"},
    {displayName: "Microsoft Soundscape", blurb: "Navigating Urban Spaces in Audio Augmented Reality", docId: "soundscape", img:"soundscape"},
    {displayName: "ESA Voice App", blurb: "Longitudinal voice analysis for monitoring wellness of Astronauts in isolation", docId: "longva", img:"longva"},
    {displayName: "This Page", blurb: "A portfolio page built in Vue+Bootstrap and hosted on Netlify", docId: "janmade", img:"janmade"},
]